-- Property Type seed data
INSERT INTO tbl_property_types (property_type_code, property_type_name, description, created_by, created_on) VALUES ('STA', 'Standard', 'Standard Property', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_property_types (property_type_code, property_type_name, description, created_by, created_on) VALUES ('SMALL_HMO', 'Small HMO', 'Small Houses in Multiple Occupation Property', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_property_types (property_type_code, property_type_name, description, created_by, created_on) VALUES ('LARGE_HMO', 'Large HMO', 'Large Houses in Multiple Occupation Property', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_property_types (property_type_code, property_type_name, description, created_by, created_on) VALUES ('SMALL_MUFB', 'Small MUFB', 'Small Multi-Unit Freehold Block Property', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_property_types (property_type_code, property_type_name, description, created_by, created_on) VALUES ('LARGE_MUFB', 'Large MUFB', 'Large Multi-Unit Freehold Block Property', 'System', CURRENT_TIMESTAMP());

-- Borrower Type seed data
INSERT INTO tbl_borrower_types (borrower_type_code, borrower_type_name, description, created_by, created_on) VALUES ('IND', 'Individual', 'Individual Owner', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_borrower_types (borrower_type_code, borrower_type_name, description, created_by, created_on) VALUES ('LTD', 'Limited Company', 'Limited Company Owner', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_borrower_types (borrower_type_code, borrower_type_name, description, created_by, created_on) VALUES ('SPV', 'Limited Liability Partnership', 'Limited Liability Partnership Owner', 'System', CURRENT_TIMESTAMP());

-- Borrower Type seed data
INSERT INTO tbl_nationality_types (nationality_type_code, nationality_type_name, description, created_by, created_on) VALUES ('CIT', 'British Citizen', 'British Citizens', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_nationality_types (nationality_type_code, nationality_type_name, description, created_by, created_on) VALUES ('EXPAT', 'Expatriate', 'Expatriate - Non- British nationals', 'System', CURRENT_TIMESTAMP());

-- Rate Type seed data
INSERT INTO tbl_product_types (product_type_code, product_type_name, description, created_by, created_on) VALUES ('FRY2', '2 Fixed Rate Years', 'Fixed rate for 2 years', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_product_types (product_type_code, product_type_name, description, created_by, created_on) VALUES ('FRY3', '3 Fixed Rate Years', 'Fixed rate for 3 years', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_product_types (product_type_code, product_type_name, description, created_by, created_on) VALUES ('FRY5', '5 Fixed Rate Years', 'Fixed rate for 5 years', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_product_types (product_type_code, product_type_name, description, created_by, created_on) VALUES ('TRA', 'Tracker Rate', 'Tracker rate', 'System', CURRENT_TIMESTAMP());

-- Rental Coverage seed data
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 1, 1, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 1, 2, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 1, 3, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 1, 4, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 1, 5, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 2, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 2, 2, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 2, 3, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 2, 4, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 2, 5, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 3, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 3, 2, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 3, 3, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 3, 4, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (1, 3, 5, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 1, 1, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 1, 2, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 1, 3, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 1, 4, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 1, 5, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 2, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 2, 2, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 2, 3, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 2, 4, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 2, 5, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 3, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 3, 2, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 3, 3, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 3, 4, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (2, 3, 5, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 1, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 2, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 3, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 4, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 5, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 2, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 3, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 4, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 5, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 2, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 3, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 4, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 5, 130, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 1, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 2, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 3, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 4, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 1, 5, 140, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 2, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 3, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 4, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 2, 5, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 1, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 2, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 3, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 4, 125, 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_rental_coverages (product_type_id, borrower_type_id, property_type_id, rental_coverage, created_by, created_on) VALUES (3, 3, 5, 125, 'System', CURRENT_TIMESTAMP());


-- Loan Products
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY2_75', 'Standard 2 Year Fixed, 75 LTV', 25, 1, 1, 1, 3.09, 4.75, 75, 1.75, 'Standard 2 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY2_80', 'Standard 2 Year Fixed, 80 LTV', 25, 1, 1, 1, 3.49, 4.75, 80, 1.75, 'Standard 2 Year Fixed Rate for 80 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY3_75', 'Standard 3 Year Fixed, 75 LTV', 25, 2, 1, 1, 3.39, 4.75, 75, 1.75, 'Standard 3 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY3_80', 'Standard 3 Year Fixed, 80 LTV', 25, 2, 1, 1, 3.79, 4.75, 80, 1.75, 'Standard 3 Year Fixed Rate for 80 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY5_65', 'Standard 5 Year Fixed, 65 LTV', 25, 3, 1, 1, 3.59, 4.75, 65, 1.75, 'Standard 5 Year Fixed Rate for 65 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY5_75', 'Standard 5 Year Fixed, 75 LTV', 25, 3, 1, 1, 3.75, 4.75, 75, 1.75, 'Standard 5 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_FRY5_80', 'Standard 5 Year Fixed, 80 LTV', 25, 3, 1, 1, 3.99, 4.75, 80, 2, 'Standard 5 Year Fixed Rate for 80 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_TRA_65', 'Standard Tracker, 65 LTV', 25, 4, 1, 1, 0, 3.10, 65, 1.75, 'Standard Tracker Rate for 65 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_TRA_75', 'Standard Tracker, 75 LTV', 25, 4, 1, 1, 0, 3.25, 75, 1.75, 'Standard Tracker Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('STANDARD_TRA_80', 'Standard Tracker, 80 LTV', 25, 4, 1, 1, 0, 3.5, 80, 2, 'Standard Tracker Rate for 80 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('SMALL_HMO_FRY2_75', 'Small HMO 2 Year Fixed, 75 LTV', 25, 1, 2, 1, 3.09, 4.75, 75, 2, 'Small HMO 2 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('SMALL_MUFB_FRY2_75', 'Small MUFB 2 Year Fixed, 75 LTV', 25, 1, 4, 1, 3.09, 4.75, 75, 2, 'Small MUFB 2 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('SMALL_HMO_FRY5_75', 'Small HMO 5 Year Fixed, 75 LTV', 25, 3, 2, 1, 3.75, 4.75, 75, 2, 'Small HMO 5 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('SMALL_MUFB_FRY5_75', 'Small MUFB 5 Year Fixed, 75 LTV', 25, 3, 4, 1, 3.75, 4.75, 75, 2, 'Small MUFB 5 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('SMALL_HMO_TRA_75', 'Small HMO Tracker, 75 LTV', 25, 4, 2, 1, 0, 3.25, 75, 2, 'Small HMO Tracker Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('SMALL_MUFB_TRA_75', 'Small MUFB Tracker, 75 LTV', 25, 4, 4, 1, 0, 3.25, 75, 2, 'Small MUFB Tracker Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('LARGE_HMO_FRY2_75', 'Large HMO 2 Year Fixed, 75 LTV', 25, 1, 3, 1, 3.59, 4.75, 75, 2, 'Large HMO 2 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('LARGE_MUFB_FRY2_75', 'Large MUFB 2 Year Fixed, 75 LTV', 25, 1, 5, 1, 3.59, 4.75, 75, 2, 'Large MUFB 2 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('LARGE_HMO_FRY5_75', 'Large HMO 5 Year Fixed, 75 LTV', 25, 3, 3, 1, 3.99, 4.75, 75, 2, 'Large HMO 5 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('LARGE_MUFB_FRY5_75', 'Large MUFB 5 Year Fixed, 75 LTV', 25, 3, 5, 1, 3.99, 4.75, 75, 2, 'Large MUFB 5 Year Fixed Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('LARGE_HMO_TRA_75', 'Large HMO Tracker, 75 LTV', 25, 4, 3, 1, 0, 3.40, 75, 2, 'Large HMO Tracker Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('LARGE_MUFB_TRA_75', 'Large MUFB Tracker, 75 LTV', 25, 4, 5, 1, 0, 3.40, 75, 2, 'Large MUFB Tracker Rate for 75 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('EXPAT_FRY2_70', 'Expat 2 Year Fixed, 70 LTV', 25, 1, 0, 2, 3.99, 4.75, 70, 2, 'Expatriate 2 Year Fixed Rate for 70 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('EXPAT_FRY5_70', 'Expat 5 Year Fixed, 70 LTV', 25, 3, 0, 2, 3.99, 4.29, 70, 2, 'Expatriate 5 Year Fixed Rate for 70 LTV', 'System', CURRENT_TIMESTAMP());
INSERT INTO tbl_products (product_code, product_name, tenure, product_type_id, property_type_id, nationality_type_id, fixed_borrowing_rate, tracker_borrowing_rate, product_ltv, product_fee, description, created_by, created_on) VALUES ('EXPAT_TRA_70', 'Expat Tracker, 70 LTV', 25, 4, 0, 2, 0, 3.40, 70, 2, 'Expatriate Tracker Rate for 70 LTV', 'System', CURRENT_TIMESTAMP());



